name: build
on:
  push:
    branches: [ hexo ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: gen readme
        run: python3 genIndex.py
      - name: gen update time
        run: |
          export TZ='Asia/Shanghai'
          sed -i "s/UpdateTime/`date '+%Y-%m-%d %H:%m'` UTC+8/g" ./themes/yelee/layout/_partial/footer.ejs
          sed -i "s/UpdateTime/`date '+%Y-%m-%d %H:%m'` UTC+8/g" ./_config.yml
          #sed -i "s/UpdateTime/`date -R`/g" ./themes/yelee/layout/_partial/footer.ejs   
          
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup Git
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        run: |
          #mkdir -p ~/.ssh/
          #echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          #chmod 600 ~/.ssh/id_rsa
          sed -i "s/gh_token/${ACCESS_TOKEN}/g" ./_config.yml
          git config --global user.name "mbinary"
          git config --global user.email "zhuheqin1@gmail.com"
      - name: install hexo
        run: |
          npm i -g hexo-cli
          npm i
      - name: instal hexo pulgins
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-filter-github-emojis --save
          npm install hexo-filter-highlight --save
          npm install hexo-front-matter --save
          npm install hexo-generator-baidu-sitemap --save
          npm install hexo-generator-category --save
          npm install hexo-generator-searchdb --save
          npm install hexo-generator-sitemap --save
          npm install hexo-generator-search --save
          npm install hexo-generator-feed --save
          npm install hexo-generator-archive --save
          npm install hexo-helper-live2d --save
          npm install hexo-i18n --save
          npm install hexo-pagination --save
          npm install hexo-renderer-ejs --save
          npm install hexo-renderer-mathjax --save
          npm install hexo-renderer-stylus --save
          npm install hexo-wordcount --save
      - name: deploy
        run: |
          #rm -rf .deploy_git
          #rm ~/.ssh/id_rsa
          hexo deploy
